### ISSUE TITLE
Can't click "save" on existing task or new task after upgrading to latest version

### ISSUE THREAD

**Issue by redlance7** [dotproject/dotProject#156]
I just upgraded to 2.2.2, running PHP 7.4 and I"m discovering that I can't make changes to any existing tasks, and I can't save a new task.  I have full admin credentials with full permissions on all modules.  Clicking save just doesn't do anything.  I can work all around the rest of the task form and do all kinds of stuff, I just can't click save.

**Comment by GwynethLlewelyn** [comment]
Ah! I have encountered the same issue. It's weird indeed. So far, I've noticed that the 'save' button is supposed to trigger some JavaScript, which, in turn, does the actual saving. But for some reason, this script seems not to be running. I'm trying to see what causes it and fix it ASAP.

**Comment by redlance7** [comment]
I got tired of fighting with it so I uninstalled dotproject and reinstalled the instance and just started over from scratch. Working now, so that tells me that something just didn't go well during the upgrade.

**Comment by GwynethLlewelyn** [comment]
Oh! That's actually interesting.

I've tracked down the issue to the JavaScript file `modules/tasks/addedit.js`. On modern browsers, it throws an error:
```console
addedit.js:631 Uncaught TypeError: Cannot read property 'length' of undefined
    at FormDefinition.saveDepend [as saveHandler] (addedit.js:631)
    at FormDefinition.fd_save [as save] (addedit.js:503)
    at submitIt (addedit.js:86)
    at HTMLInputElement.onclick (index.php?m=tasks&a=addedit&task_project=1:203)
```
This error is not obvious, and not trivial to fix, because `addedit.js` is just  _part_ of the JavaScript code. The actual initialisation happens in PHP, on files such as `modules/tasks/ae_resource.php` (there may be more calling the same script). Apparently, this initialisation is not necessarily happening correctly and/or happens 'out of order', so when the code in `addedit.js` is actually executed, it hasn't got everything properly initialised. As far as I can see, the culprit seems to be `var projTasksWithEndDates=new Array();` — perhaps not the only one, though — which isn't getting properly assigned to an `Array()` (it remains set as `undefined`), and, as such, misses the `length` property.

I'm even worse at debugging JavaScript than PHP ('worse', in this context, means 'slow'...) so it'll take some time to do a proper workaround.

Then again, if you managed to get everything fixed just by reinstalling, I guess you could close this issue, marked 'solved' 😉
