### ISSUE TITLE
Installation do not available 

### ISSUE THREAD

**Issue by KingsleyEgia** [dotproject/dotProject#26]
This msg from the install process.
What is the change to php.ini that is required?
thanks Peter
=============
Session Save Path writable? | Warning:  is_dir(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/c/ck200.live/public_html/dotproject/install/vw_idx_check.php on line 81  Warning:  is_dir(): Unable to find the wrapper "tcp" - did you forget to enable it when you configured PHP? in /var/sites/c/ck200.live/public_html/dotproject/install/vw_idx_check.php on line 81  Fatal: tcp://10.168.1.55:11211?persistent=0&weight=1&timeout=5&retry_interval=15 not existing or not writable
-- | --

**Comment by ajdonnison** [comment]
What sort of system have you got there?  It would appear that your session.save_path in php.ini is set to the string `tcp://10.168.1.55:11211?persistent=0&weight=1&timeout=5&retry_interval=15` - and you don't have the required tcp wrapper installed so that is_dir can check (and it would still fail anyway, I believe).

**Comment by ajdonnison** [comment]
No response, closing.
