### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by fatabek** [dotproject/dotProject#46]
If we write "utf-8" in the "locales.php" file in the "en" directory. Gantt chart characters are not show correctly. Becuase jpgraphs "LANGUAGE_CHARSET" comparison is case-insensitive therefore we must be write "UTF-8"  in "locales.php" file for show correctly characters in Gantt charts. In devel branch "locale.php" contain small case like "utf-8".

**Comment by ajdonnison** [comment]
Case-insensitive means that either utf-8 or UTF-8 will work.  Are you using an external jpgraph library or the one provided with dotProject?  If external what version?  Can you reference the actual code that makes the comparison that you believe requires the uppercase version?

**Comment by fatabek** [comment]
No, I am not using external jpgraph library. 

with smallcase:

![wsmlletter](https://user-images.githubusercontent.com/41823969/50880562-e2852980-13ef-11e9-88cf-7d18934b696f.PNG)


with uppercase:


![wbigletter](https://user-images.githubusercontent.com/41823969/50880582-f466cc80-13ef-11e9-9821-1d2b7fcab1a2.PNG)

**Comment by ajdonnison** [comment]
I suspect the problem is not in jpgraph, but in the projectdesigner gantt.php file where it checks if the locale uses utf-8 (lowercase) and if not will do a conversion *to* utf-8.  This suggests that somewhere along the way the input is not actually utf-8.  Can you check the character encoding on your database?  That can cause these sorts of issues - remember with the database that there are three character encoding points - the connection charset, the database default charset and the table charset.  If any of them don't match the database will attempt conversion.

Another possibility is that the conversion is being undone by jpgraph.  You might want to grab the last change I pushed and try that with the lowercase utf-8 version.

**Comment by fatabek** [comment]
Hello,

I came across a new solution and it is much more accurate, the person who found it is Murat Özalp and its explanation is "http://web.bilecik.edu.tr/murat-ozalp/2010/04/13/dotproject-gantt-semasinda-turkce-karakter -problem/" link. But the explanation is in Turkish, so if we summarize the explanation briefly:

1) In the file "./modules/projects/gantt.php"
"if ($locale_char_set=='utf-8′ && function_exists('utf8_decode')) {"
expression
"if ($locale_char_set!='utf-8′ && function_exists('utf8_decode')) {"
It is sufficient to replace it with

The same change should be made in the "./modules/tasks/gantt.php" file. It can also be stretched in the "gantt.php" file of the "project designer" module, but I could not try it.
