### ISSUE TITLE
PHP Error after installation

### ISSUE THREAD

**Issue by joaovramos** [dotproject/dotProject#72]
Hi, 

After to install, when I put to login, show this message:

Recoverable fatal error: ini_set(): Cannot set 'user' save handler by ini_set() or session_module_name() in C:\xampp\htdocs\dotProject\includes\session.php on line 195

![image](https://user-images.githubusercontent.com/7526167/59427789-db54b400-8db1-11e9-85df-83d3f66960b6.png)

Do not showed any error during the installation.

**Comment by Givo29** [comment]
@joaovramos, it seems to be an incompatibility with the version of PHP you may be running. If you're running PHP 7.2 or higher, I've seen suggested fixes that could include commenting out line 195 `ini_set('session.save_handler', 'user');` or dropping back to an older version of PHP. I'd suggest seeing what happens when that line is commented out first.

[Similar issue](https://github.com/symphonycms/symphony-2/issues/2783)

**Comment by joaovramos** [comment]
@Givo29, worked commenting the line.

thanks

**Comment by Givo29** [comment]
all good, since it's fixed please close the issue :)
